"""
Automated Play Console background-location demo recording.
Drives the child app on emulator-5554, captures via adb screenrecord.

Usage:
    python record_demo.py <PAIRING_CODE>

PAIRING_CODE must be the exact 8-character code generated by the parent app
(no dash). Code expires fast — generate it right before running.
"""
import subprocess
import sys
import time
import re
import xml.etree.ElementTree as ET
from pathlib import Path

# Force UTF-8 stdout so Mongolian Cyrillic log lines don't crash on Windows cp1252
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except AttributeError:
    pass

ADB = r"C:\Users\friday\AppData\Local\Android\Sdk\platform-tools\adb.exe"
TMP_DUMP_LOCAL = Path(__file__).parent / "_uidump.xml"
TMP_VIDEO_LOCAL = Path(__file__).parent / "demo-scripted.mp4"
DEVICE_VIDEO_PATH = "/sdcard/demo.mp4"


def adb(*args, shell=False, check=True, timeout=15):
    cmd = [ADB]
    if shell:
        cmd.append("shell")
    cmd.extend(str(a) for a in args)
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if check and result.returncode != 0 and result.stderr:
        print(f"[adb warn] {' '.join(args)} -> {result.stderr.strip()[:200]}")
    return result


def dump_ui():
    adb("uiautomator", "dump", "/sdcard/dump.xml", shell=True)
    # adb pull with explicit byte read to avoid Windows path mangling
    adb("pull", "/sdcard/dump.xml", str(TMP_DUMP_LOCAL))
    if not TMP_DUMP_LOCAL.exists():
        return None
    return TMP_DUMP_LOCAL.read_text(encoding="utf-8", errors="replace")


def parse_bounds(bounds_str):
    """[x1,y1][x2,y2] -> (cx, cy)"""
    m = re.match(r"\[(\d+),(\d+)\]\[(\d+),(\d+)\]", bounds_str)
    if not m:
        return None
    x1, y1, x2, y2 = map(int, m.groups())
    return (x1 + x2) // 2, (y1 + y2) // 2


def find_by_text(xml_str, exact_text):
    """Find a node with exact text match, return center coords."""
    if not xml_str:
        return None
    # Use ET parsing — safer than regex for nested attrs
    try:
        root = ET.fromstring(xml_str)
    except ET.ParseError:
        return None
    for node in root.iter("node"):
        if node.get("text") == exact_text:
            return parse_bounds(node.get("bounds", ""))
    return None


def find_by_text_contains(xml_str, substring):
    """Find first node whose text contains the substring (case-insensitive)."""
    if not xml_str:
        return None
    try:
        root = ET.fromstring(xml_str)
    except ET.ParseError:
        return None
    sub_lower = substring.lower()
    for node in root.iter("node"):
        text = (node.get("text") or "").lower()
        if sub_lower and sub_lower in text:
            return parse_bounds(node.get("bounds", ""))
    return None


def find_by_resource_id(xml_str, resource_id_suffix):
    if not xml_str:
        return None
    try:
        root = ET.fromstring(xml_str)
    except ET.ParseError:
        return None
    for node in root.iter("node"):
        if node.get("resource-id", "").endswith(resource_id_suffix):
            return parse_bounds(node.get("bounds", ""))
    return None


def tap(x, y, label=""):
    print(f"  tap ({x}, {y}) {label}")
    adb("input", "tap", str(x), str(y), shell=True)


def tap_text(text, wait=2.0, label=""):
    xml = dump_ui()
    coords = find_by_text(xml, text)
    if coords is None:
        coords = find_by_text_contains(xml, text)
    if coords is None:
        print(f"  [WARN] text not found: '{text}' (label={label})")
        return False
    tap(*coords, label=label or text)
    time.sleep(wait)
    return True


def main():
    if len(sys.argv) < 2:
        print("Usage: python record_demo.py <PAIRING_CODE>")
        sys.exit(1)
    code = sys.argv[1].strip().upper()
    if len(code) != 8:
        print(f"[WARN] pairing code is {len(code)} chars, expected 8 — continuing anyway")

    print("=" * 60)
    print("Scripted Play Console demo recording")
    print(f"Pairing code: {code}")
    print("=" * 60)

    # Step 0: Reset device + app state, initial GPS, disable Gboard.
    # The previous run's notification-shade swipe leaves Quick Settings open
    # on top of everything. Press HOME twice to collapse any stale system UI
    # so the next launch lands cleanly. Also disable Gboard so its left-edge
    # floating panel on Android 16 doesn't block taps to the leftmost box.
    print("\n[0] Resetting device state, clearing app, GPS, disabling Gboard")
    adb("shell", "input", "keyevent", "KEYCODE_HOME")
    time.sleep(0.3)
    adb("shell", "input", "keyevent", "KEYCODE_HOME")  # double-tap collapses QS
    time.sleep(0.5)
    adb("shell", "pm", "clear", "com.parenthelper.child")
    adb("emu", "geo", "fix", "106.917693", "47.918873")
    adb("shell", "ime", "disable",
        "com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME")
    adb("shell", "settings", "put", "secure", "default_input_method",
        "com.google.android.tts/com.google.android.apps.speech.tts.googletts.settings.asr.voiceime.VoiceInputMethodService")
    time.sleep(1)

    # Remove any stale recording
    adb("shell", "rm", "-f", DEVICE_VIDEO_PATH)

    # Step 1: Start screen recording in background
    print("\n[1] Starting screen recording (max 120s)")
    # Use Popen so we can stop with SIGINT later
    recorder = subprocess.Popen(
        [ADB, "shell", "screenrecord", "--time-limit", "120",
         "--bit-rate", "8000000", DEVICE_VIDEO_PATH],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    time.sleep(1.5)  # give screenrecord time to start

    # Step 2: Launch app
    print("\n[2] Launching app")
    adb("shell", "am", "start", "-n",
        "com.parenthelper.child/.ui.onboarding.SplashActivity")
    time.sleep(3.5)  # splash animation + transition

    # Step 3: Enter pairing code character-by-character
    # PairingActivity auto-focuses box 1 on launch (postDelayed 150ms) and the
    # afterTextChanged listener advances focus to the next box after each char.
    # So we never need to tap individual boxes — only type. This sidesteps
    # collisions with Gboard's left-edge floating panel on Android 16.
    print("\n[3] Entering pairing code (no per-box taps — relying on auto-advance)")
    for ch in code[:8]:
        adb("shell", "input", "text", ch)
        time.sleep(0.2)
    time.sleep(1.0)

    # Step 4: Tap ХОЛБОХ (Connect) button
    print("\n[4] Tapping ХОЛБОХ")
    tap(540, 1207, label="ХОЛБОХ (connect)")
    time.sleep(4)  # API call + navigate to PairingSuccessActivity

    # Step 5: PairingSuccessActivity — tap Үргэлжлүүлэх (Continue)
    print("\n[5] Tapping Үргэлжлүүлэх on success screen")
    tap_text("Үргэлжлүүлэх", wait=2.5, label="continue success")

    # Step 6: Onboarding step 1 (Usage Stats) — Skip
    print("\n[6] Skipping Usage Stats step")
    tap_text("Дараа тохируулах", wait=1.5, label="skip usage stats")

    # Step 7: Onboarding step 2 (Device Admin) — Skip
    print("\n[7] Skipping Device Admin step")
    tap_text("Дараа тохируулах", wait=1.5, label="skip device admin")

    # Step 8: Onboarding step 3 (Location) — Grant
    print("\n[8] Tapping Зөвшөөрөл олгох on Location step")
    tap_text("Зөвшөөрөл олгох", wait=2.0, label="grant location")

    # Step 9: PROMINENT DISCLOSURE dialog — hold visible 5 seconds
    print("\n[9] Holding prominent disclosure dialog for 5 sec")
    time.sleep(5)

    # Step 10: Tap Үргэлжлүүлэх on disclosure dialog
    print("\n[10] Tapping Үргэлжлүүлэх on disclosure dialog")
    tap_text("Үргэлжлүүлэх", wait=2.5, label="continue disclosure")

    # Step 11: System foreground location dialog — pick "While using the app"
    print("\n[11] System foreground location: while using the app")
    # Try multiple known button texts (varies by Android version)
    xml = dump_ui()
    fg_candidates = [
        "While using the app",
        "Only this time",
        "Allow only while using the app",
        "Аппыг ашиглаж байх үед",
    ]
    for label in fg_candidates:
        coords = find_by_text(xml, label) or find_by_text_contains(xml, label)
        if coords:
            tap(*coords, label=f"foreground: {label}")
            break
    else:
        print("  [WARN] foreground permission button not found")
    time.sleep(3)

    # Step 11b: POST_NOTIFICATIONS dialog (Android 13+) appears in the same
    # multi-permission launcher. Tap Allow if it shows up.
    print("\n[11b] POST_NOTIFICATIONS dialog (if present): Allow")
    xml = dump_ui()
    notif_visible = (
        find_by_text_contains(xml, "notifications") is not None
        or find_by_text_contains(xml, "Prime Kids to send") is not None
    )
    if notif_visible:
        # Find the "Allow" button specifically (not "Don't allow")
        coords = find_by_text(xml, "Allow")
        if coords:
            tap(*coords, label="notifications: Allow")
        else:
            print("  [WARN] notifications Allow button not found")
        time.sleep(2)
    else:
        print("  notifications dialog not shown — skipping")

    # Step 12: Background location settings page — pick "Allow all the time"
    # Background settings page takes longer to render than the inline dialog.
    # Poll for the right label for up to 8 seconds.
    print("\n[12] Background location: Allow all the time")
    bg_candidates = [
        "Allow all the time",
        "Always allow",
        "Бүх үед зөвшөөрөх",
    ]
    bg_found = False
    for _ in range(8):
        time.sleep(1)
        xml = dump_ui()
        for label in bg_candidates:
            coords = find_by_text(xml, label) or find_by_text_contains(xml, label)
            if coords:
                tap(*coords, label=f"background: {label}")
                bg_found = True
                break
        if bg_found:
            break
    if not bg_found:
        print("  [WARN] background 'all the time' option not found after 8s polling")
        if xml:
            import re as _re
            texts = sorted(set(_re.findall(r'text="([^"]+)"', xml or "")))
            print(f"  visible texts: {[t for t in texts if t.strip()][:25]}")
    time.sleep(3)

    # Step 13: Go back to app (if settings opened a separate page)
    print("\n[13] Going back to app")
    adb("shell", "input", "keyevent", "KEYCODE_BACK")
    time.sleep(2)

    # Step 14: Press home + open notification shade
    print("\n[14] Home + notification shade")
    adb("shell", "input", "keyevent", "KEYCODE_HOME")
    time.sleep(1.5)
    # Swipe from very top down — twice to get full shade
    adb("shell", "input", "swipe", "540", "0", "540", "1500", "300")
    time.sleep(0.5)
    adb("shell", "input", "swipe", "540", "0", "540", "1500", "300")
    time.sleep(3)

    # Step 15: Mock GPS movement to demonstrate location updates
    print("\n[15] Mocking GPS movement")
    adb("emu", "geo", "fix", "106.926500", "47.911000")
    time.sleep(2)
    adb("emu", "geo", "fix", "106.935800", "47.905200")
    time.sleep(2)

    # Step 16: Stop screen recording
    print("\n[16] Stopping screen recording")
    # SIGINT to the device-side screenrecord process
    adb("shell", "pkill", "-SIGINT", "screenrecord")
    time.sleep(2)
    try:
        recorder.wait(timeout=10)
    except subprocess.TimeoutExpired:
        recorder.kill()

    # Step 17: Pull file
    print("\n[17] Pulling video file")
    if TMP_VIDEO_LOCAL.exists():
        TMP_VIDEO_LOCAL.unlink()
    adb("pull", DEVICE_VIDEO_PATH, str(TMP_VIDEO_LOCAL))
    if TMP_VIDEO_LOCAL.exists():
        size_mb = TMP_VIDEO_LOCAL.stat().st_size / 1024 / 1024
        print(f"\nDONE. Video at: {TMP_VIDEO_LOCAL} ({size_mb:.2f} MB)")
    else:
        print("\n[ERROR] video not pulled — check emulator")
        sys.exit(1)


if __name__ == "__main__":
    main()
